DROP DATABASE IF EXISTS burgersDB;
CREATE DATABASE burgersDB;

USE burgersDB;

CREATE TABLE burgers
(
    id INT NOT NULL
    AUTO_INCREMENT,
  burgerName VARCHAR
    (45) NOT NULL,
    devoured BOOLEAN DEFAULT FALSE,
  PRIMARY KEY
    (id)
);
